update(pydantic)
Clinical-Genomics/genotype-api pull request #104
Opened 2024-03-14 13:54 UTC by ChrOertlin

### Added

Update to pydantic v2

### Changed

### Fixed

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2024-03-14 14:41 UTC, ChrOertlin commented on genotype_api/database/models.py
> -    email: EmailStr = Field(index=True, unique=True)
This type does not seem be to supported and breaks if used. We possible need to move the email validation forward to where we create a user.

```
  File "/Users/christian/Documents/clinicalGenomics/genotype-api/venv/lib/python3.11/site-packages/sqlmodel/main.py", line 607, in get_sqlalchemy_type
    raise ValueError(f"{type_} has no matching SQLAlchemy type")
ValueError: <class 'pydantic.networks.EmailStr'> has no matching SQLAlchemy type

```

2024-03-14 15:05 UTC, henrikstranneheim approved these changes
Fantastic, 👍

2024-03-14 15:05 UTC, henrikstranneheim commented on genotype_api/database/models.py
> -    email: EmailStr = Field(index=True, unique=True)
👍

2024-03-14 15:05 UTC, henrikstranneheim commented on requirements.txt
> +SQLAlchemy
⭐ Nice

2024-03-14 15:40 UTC, islean commented on genotype_api/database/models.py
> +    chrom: str | None = Field(max_length=5)
I think we need to be careful with changes to these behaviours. In Pydantic v1 this would mean that it is optional as input and output, but in v2 you need to give a default to keep the same behaviour.

2024-03-14 15:41 UTC, ChrOertlin commented on genotype_api/database/models.py
> +    chrom: str | None = Field(max_length=5)
These are `SQLmodels` not pydantic `BaseModels`

2024-03-14 15:42 UTC, islean requested changes
There is a subtlety (or at least I am quite certain there is) in that optionals have changed behaviour. Previously `a: str | None` would mean that you could instantiate the BaseModel without `a` set. That is not the case in Pydantic v2. The same behaviour would be achieved by `a: str | None = None`. Please double check if I am correct though.

edit: I was mistaken.

2024-03-14 15:45 UTC, islean approved these changes
Nevermind, thought SQLModels extended BaseModels! Looks good!

2024-03-18 07:50 UTC, ChrOertlin commented
This proves to be more of a hassle than I thought

2024-04-05 13:52 UTC, ChrOertlin commented
Closing, done in another PR

2024-04-05 13:52 UTC, closed without merging